version: '2.0'

services:

  api:
    container_name: api-smart-ranking
    build: .
    ports:
      - ${PORT}:${PORT}
    volumes:
      - .:/home/api

  database:
    container_name: api_smart_ranking_db
    image: mongo
    ports:
    - ${MONGO_PORT}:${MONGO_PORT}

  redis_data_base:
    container_name: api_smart_ranking_redis_db
    image: redis:5.0.10-alpine
    ports:
      - '6379:6379'
