name: 'PR: TEST'

on:
  pull_request:
    types: ['opened', 'synchronize', 'reopened']
    branches:
      - develop
      - master

jobs:
  tests:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/setup-node@v2
      - uses: actions/checkout@v2
      - run: yarn install
      - run: yarn test
